stocks:
  - symbol: VTI
    target_percentage: 71
    description: Total US Market
    alternatives:
      - FSKAX
  - symbol: VXUS
    target_percentage: 18
    description: Total International Market
    alternatives:
      - FTIHX
  - symbol: BND
    target_percentage: 10
    description: Total Bond Market
    alternatives:
      - FXNAX
  - symbol: FBTC
    target_percentage: 1
    description: Bitcoin
